#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 645384141                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/cachly-geocaching/id645384141?uo=4                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
geocaching_link                           : https://apidevelopers.geocaching.com/partner-list

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Cachly - Geocaching                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple and Powerful Geocaching

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


link1_title                               : Help
link1_link                                : https://www.cach.ly/help
link2_title                               : Forums
link2_link                                : https://www.cach.ly/support
link3_title                               : Blog
link3_link                                : https://medium.com/@cachly
link4_title                               : Shirts & Swag
link4_link                                : https://shop.spreadshirt.com/cachly?noCache=true

# Information About Yourself
your_name                                 : Zed Said Studio LLC                               
your_link                                 : https://www.zedsaid.com                   
your_city                                 : the Pacific Northwest                             
email_address                             : support@cach.ly
facebook_username                         : groups/CachlyUserGroup                                          
twitter_username                          : cachlyapp



# Feature List                            Edit, add or remove features to be presented.
features                                  :


  - title                                 : Authorized Developer
    description                           : As an official partner app of Geocaching HQ we use the API and authenticate with geocaching.com.
    fontawesome_icon_name                 : handshake
    
  - title                                 : Premium Offline Maps
    description                           : Beautiful OSM source offline maps of the globe.
    fontawesome_icon_name                 : map
    
  - title                                 : Search the Globe
    description                           : Search for Geocaches across the globe!
    fontawesome_icon_name                 : search

  - title                                 : Create Log 
    description                           : Quickly create your log right from the app.
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Live Search Filtering
    description                           : Powerful filtering to narrow down your search.
    fontawesome_icon_name                 : filter

  - title                                 : Save Offline
    description                           : Add caches to offline lists that include powerful filtering.
    fontawesome_icon_name                 : times

  - title                                 : Highlight
    description                           : Mark caches with various colors for reference.
    fontawesome_icon_name                 : highlighter
    
  - title                                 : TB Scanner
    description                           : Quickly scan trackables using your camera.
    fontawesome_icon_name                 : bug

  - title                                 : Export GPX
    description                           : Save a GPX for use in Cachly or other apps.
    fontawesome_icon_name                 : share

  - title                                 : Text Templates
    description                           : Custom log text templates for quick usage.
    fontawesome_icon_name                 : file-alt

  - title                                 : Proximity Alert
    description                           : Get alerted when you come close to a geocache.
    fontawesome_icon_name                 : bullseye
    
  - title                                 : Apple Watch App
    description                           : Search, navigate and log right on your watch.
    fontawesome_icon_name                 : clock
    
  - title                                 : Translate Logs and Descriptions
    description                           : Options to translate to other languages.
    fontawesome_icon_name                 : language



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#31a350"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#31a350"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
